
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AP_PRO_Balladins_2_annee
{

using System;
    using System.Collections.Generic;
    
public partial class reservation
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public reservation()
    {

        this.reserv = new HashSet<reserv>();

        this.reserv1 = new HashSet<reserv>();

    }


    public int nores { get; set; }

    public Nullable<System.DateTime> datedeb { get; set; }

    public Nullable<System.DateTime> datefin { get; set; }

    public string nom { get; set; }

    public string email { get; set; }

    public Nullable<double> codeacces { get; set; }



    public virtual hotel hotel { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<reserv> reserv { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<reserv> reserv1 { get; set; }

}

}
