//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP_PRO_Balladins_2_annee
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserv
    {
        public int nores { get; set; }
        public int nohotel { get; set; }
        public int nochambre { get; set; }
    
        public virtual chambre chambre { get; set; }
        public virtual reservation reservation { get; set; }
    }
}
